language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

install:
  - rm composer.lock
  - travis_retry composer update --prefer-dist

script: vendor/bin/phpunit

allow_failures:
  - php: 7.4snapshot
